accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('signin',views.signin,name='signin'),
    path('logout',views.user_logout,name='logout'),
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('productfavorite/<int:pro_id>/',views.product_favorite,name='product_favorite'),
    path('show_product_favorite',views.show_product_favorite,name='show_product_favorite'),

]

mycoffe/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include('pages.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('products/',include('products.urls',namespace='products')),
    path('orders/',include('orders.urls',namespace='add_to_cart')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'add_to_cart'

urlpatterns=[
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),
    path('cart',views.cart,name='cart'),
    path('remove_from_cart/<int:orderdetails_id>',views.remove_from_cart,name='remove_from_cart'),
    path('add_qty/<int:orderdetails_id>',views.add_qty,name='add_qty'),
    path('sub_qty/<int:orderdetails_id>',views.sub_qty,name='sub_qty'),
    path('payment',views.payment,name='payment'),
    path('show_orders',views.show_orders,name='show_orders'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('coffee/',views.coffee,name='coffee'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns=[

    path('',views.products,name='products'),
    path('<int:pro_id>',views.product,name='product'),
    # path('product/<int:year>/<int:month>/<int:day>/<slug:name>',views.product,name='product'),
    path('search/',views.search,name='search'),

]

products/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse

# Create your models here.
class Product(models.Model):

    name=models.CharField(max_length=150)
    description=models.TextField()
    price=models.DecimalField(max_digits=6,decimal_places=2)
    photo=models.ImageField(upload_to='photos/%y/%m/%d')
    is_active=models.BooleanField(default=True)
    publish_data=models.DateTimeField(default=datetime.now)    
    

    def __str__(self):
        return self.name
    
    class Meta:
        ordering=['-publish_data']

    # def get_absolute_url(self):

    #     return reverse("products:product",args=[
    #         self.publish_data.year,
    #         self.publish_data.month,
    #         self.publish_data.day,
    #         self.name,
    #     ])

products/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product

# Create your views here.
def products(request):

    products=Product.objects.all()
    cs=request.GET.get('cs')
    if not cs:
        cs='off' 
    name=request.GET.get('searchname')
    if name:
        if cs == 'on':
            products=products.filter(name__contains=name)
        else:
            products=products.filter(name__icontains=name)

    description=request.GET.get('searchdesc')
    if description:
        if cs == 'on':
             products= products.filter(description__contains=description)
        else:
            products= products.filter(description__icontains=description)

    searchpricefrom=request.GET.get('searchpricefrom')
    searchpriceto=request.GET.get('searchpriceto')

    if searchpricefrom and searchpriceto:
        if searchpricefrom.isdigit() and searchpriceto.isdigit():
             products = products.filter(price__gte=searchpricefrom, price__lte=searchpriceto)
    # name=request.GET.get('searchpricefrom')
    # name=request.GET.get('searchpriceto')
    # name=request.GET.get('cs')
    # products=Product.objects.all()
    context={
        'products':products
    }
    return render(request,'products/products.html',context)

def product(request,pro_id):

    # product=get_object_or_404(Product,
    #                        name=name,
    #                        publish_data__year=year,
    #                        publish_data__month=month,
    #                        publish_data__day=day,)
    pro=get_object_or_404(Product,pk=pro_id)
    return render(request,'products/product.html',{'pro':pro})

def search(request):
    return render(request,'products/search.html')

templates/products/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Product details{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <form id="frmaddtocart" action="{% url 'add_to_cart:add_to_cart' %}">
        <h2 class="text-center">Product Details</h2>
        <hr>
        {% include 'partials/_alerts.html' %}
        <section>
            
              <div class="row p-5 " >

                <div class="card mb-3 w-100" >
                  <div class="row no-gutters">
                    <div class="col-md-4">
                      <img src="{{ pro.photo.url }}" class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title" id="productName">{{ pro.name }}</h5>
                        <hr>
                        <p class="card-text" id="description">{{ pro.description }}</p>
                        <hr>
                        <p class="card-text">Current Price: <span id="price" class="bg-dark text-light rounded-circle p-2">${{ pro.price }}</span></p>
                        <hr>
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#staticBackdrop">Add To Cart</button>

                        <!-- Modal -->
                        <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Select Quantity</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <label for="inputQty">Quantity: </label>
                                <input type="text" value="1" name="qty" class="form-control" id="inputQty" placeholder="" required>
                                <input type="hidden" name="pro_id" value="{{ pro.id }}">
                                <input type="hidden" name="price" value="{{ pro.price }}">
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnclose">Close</button>
                                <button  class="btn btn-warning" onclick="addtocart()">Confirm</button>
                              </div>
                            </div>
                          </div>
                        </div>
                         <!-- Modal -->
                        <a href="{%  url 'accounts:product_favorite' pro_id=pro.id %}" class="btn btn-warning text-white">
                          <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                          </svg>
                        </a>
                        <hr>
                        <a href="{% url 'products:products' %}" class="btn btn-warning">All Products</a>
                        <a href="{% url 'index' %}" class="btn btn-warning text-white">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                            <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"/>
                          </svg>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            
        </section>
    

    </form>
<script>
  function addtocart(){
    document.getElementById('btnclose').click();
    document.getElementById('frmaddtocart').submit();

  }
</script>

</div>
{% endblock %}

templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Products{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <form>
        <h2 class="text-center">Products</h2>
        <hr>

        <section>
            <div class="container-fluid">
              <div class="row p-5" >
                {% for pro in products %}
                <div>
                  <div class="card m-2" style="width: 18rem;">
                    <img src="{{ pro.photo.url }}" class="card-img-top" alt="{{ pro.name }}">
                    <div class="card-body">
                      <h5 class="card-title">{{pro.name}}</h5>
                      <p class="card-text text-truncate">{{pro.description}}.</p>
                      <a href="{% url 'products:product' pro.id %}" class="btn btn-warning">Show Details</a>
                    </div>
                  </div>
                </div>
                {% empty %}
                <h4 class="alert alert-warning">No product here,
                  <a href="{% url 'products:products' %}" class="text-dark">All products</a>
                </h4>
                {% endfor %}
              </div>
            </div>
        </section>
    

    </form>

</div>
{% endblock %}

templates/products/search.html
{% extends 'base.html' %}

{% block title %}Advanced search{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <form action="{% url 'products:products' %}">
        <h2 class="text-center">Advanced Search</h2>
        <hr>

        <div class="form-group">
            <label for="inputSearchProductName">Product Name Contains</label>
            <input type="text" name="searchname" class="form-control" id="inputSearchProductName" placeholder="espresso">
        </div>
        
        <div class="form-group">
            <label for="inputSearchProductDescription">Product Description Contains</label>
            <input type="text" name="searchdesc" class="form-control" id="inputSearchProductDescription" placeholder="coffee">
        </div>

        <div class="form-row">

            <div class="form-group col-md-6">
                <label for="inputSearchPrice1">Price Between</label>
                <input type="number" name="searchpricefrom" class="form-control" id="inputSearchPrice1" placeholder="">
            </div>

            <div class="form-group col-md-6">
                <label for="inputSearchPrice2">And</label>
                <input type="number" name="searchpriceto" class="form-control" id="inputSearchPrice2" placeholder="">
            </div>

        </div>

        <div class="form-group">
            <div class="pretty p-svg p-curve p-jelly">
                <input type="checkbox" name="cs" id="inputCaseSensitive" />
                <div class="state p-warning">
                    <!-- svg path -->
                    <svg class="svg svg-icon" viewBox="0 0 20 20">
                        <path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;"></path>
                    </svg>
                    <label>Case Sensitive</label>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-warning">Search for All</button>
    </form>

</div>
{% endblock %}