accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns=[
    path('signin',views.signin,name='signin'),
    path('logout',views.user_logout,name='logout'),
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('productfavorite/<int:pro_id>/',views.product_favorite,name='product_favorite'),
    path('show_product_favorite',views.show_product_favorite,name='show_product_favorite'),

]

mycoffe/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include('pages.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('products/',include('products.urls',namespace='products')),
    path('orders/',include('orders.urls',namespace='add_to_cart')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'add_to_cart'

urlpatterns=[
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),
    path('cart',views.cart,name='cart'),
    path('remove_from_cart/<int:orderdetails_id>',views.remove_from_cart,name='remove_from_cart'),
    path('add_qty/<int:orderdetails_id>',views.add_qty,name='add_qty'),
    path('sub_qty/<int:orderdetails_id>',views.sub_qty,name='sub_qty'),
    path('payment',views.payment,name='payment'),
    path('show_orders',views.show_orders,name='show_orders'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('coffee/',views.coffee,name='coffee'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns=[

    path('',views.products,name='products'),
    path('<int:pro_id>',views.product,name='product'),
    # path('product/<int:year>/<int:month>/<int:day>/<slug:name>',views.product,name='product'),
    path('search/',views.search,name='search'),

]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
from creditcards.models import CardNumberField,CardExpiryField,SecurityCodeField
# Create your models here.
class Order(models.Model):

    user=models.ForeignKey(User,on_delete=models.CASCADE)
    order_date=models.DateTimeField()
    details=models.ManyToManyField(Product,through='OrderDetails')
    is_finished=models.BooleanField()
    total=0
    items_count=0

    def __str__(self):
        return f"User: {self.user.username}, Order id: {self.id}"
    
class OrderDetails(models.Model):

    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=6,decimal_places=2)
    quantity=models.IntegerField()

    def __str__(self):
        return f"User: {self.order.user.username} Product: {self.product.name} Order id: {self.order.id}"
    
    class Meta:
        ordering=['-id']

class Payment(models.Model):

    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    shipment_address=models.CharField(max_length=150)
    shipment_phone=models.CharField(max_length=50)
    card_number=CardNumberField()
    expire=CardExpiryField()
    security=SecurityCodeField()

orders/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from products.models import Product
from .models import Order,OrderDetails,Payment
from django.utils import timezone

def add_to_cart(request):

    if 'pro_id' in request.GET and 'price' in request.GET and 'qty' in request.GET and request.user.is_authenticated and not request.user.is_anonymous:
        # order=Order.objects.create(user=request.user,order_date=timezone.now,is_finished=False)
        pro_id=request.GET['pro_id']
        qty=request.GET['qty']

        order=Order.objects.filter(user=request.user,is_finished=False)

        if not Product.objects.all().filter(pk=pro_id).exists():
            return redirect('products:products')
        
        pro=Product.objects.get(pk=pro_id)

        if order:
            old_order=Order.objects.get(user=request.user,is_finished=False)
            
            if OrderDetails.objects.all().filter(order=old_order,product=pro).exists():
                orderDetail=OrderDetails.objects.get(order=old_order,product=pro)
                orderDetail.quantity+=int(qty)
                orderDetail.save()
            else:
                orderDetails=OrderDetails.objects.create(order=old_order,product=pro,price=pro.price,quantity=qty)
            messages.success(request,'Was added to cart for old order')


        else:
            new_order=Order.objects.create(user=request.user,order_date=timezone.now(),is_finished=False)
            OrderDetails.objects.create(order=new_order,product=pro,price=pro.price,quantity=qty)
            messages.success(request,'Was added to cart for new order')


        return redirect('products:product',pro_id=pro_id)
    else:
        if 'pro_id' in request.GET:

            messages.error(request,'You musr be logged in')
            pro_id = request.GET.get('pro_id')
            return redirect('products:product',pro_id=pro_id)
        else: 
            return redirect('index')
    
def cart(request):
    context=None
    if request.user.is_authenticated and not request.user.is_anonymous:
        if Order.objects.all().filter(user=request.user,is_finished=False).exists():

            order=Order.objects.get(user=request.user,is_finished=False)

            orderdetails=OrderDetails.objects.all().filter(order=order)
            total=0
            for orderdetail in orderdetails:
                total+=orderdetail.price * orderdetail.quantity
            context={
                'orderdetails':orderdetails,
                'order':order,
                'total':total,
            }
    return render(request,'orders/cart.html',context)

def remove_from_cart(request,orderdetails_id):
    
    if request.user.is_authenticated and not request.user.is_anonymous and orderdetails_id:

        orderdetails=OrderDetails.objects.get(id=orderdetails_id)

        if request.user.id == orderdetails.order.user.id:
             
            orderdetails.delete()

    return redirect('add_to_cart:cart')

def add_qty(request,orderdetails_id):

    if request.user.is_authenticated and not request.user.is_anonymous and orderdetails_id:

        orderdetails=OrderDetails.objects.get(id=orderdetails_id)
        if request.user.id == orderdetails.order.user.id:

            orderdetails.quantity +=1
            orderdetails.save()

    return redirect('add_to_cart:cart')
 
def sub_qty(request,orderdetails_id):

    if request.user.is_authenticated and not request.user.is_anonymous and orderdetails_id:

        orderdetails=OrderDetails.objects.get(id=orderdetails_id)
        
        if request.user.id == orderdetails.order.user.id:

            if orderdetails.quantity > 1:

                orderdetails.quantity -=1
                orderdetails.save()
            
    return redirect('add_to_cart:cart')

def payment(request):
    context=None
    ship_address=None
    ship_phone=None
    card_number=None
    expire=None
    security_code=None
    is_added=None
    

    if request.method == 'POST' and 'btnpayment' in request.POST and 'ship_address' in request.POST and 'ship_phone' in request.POST and 'card_number' in request.POST and 'expire' in request.POST and 'security_code' in request.POST:

        ship_address=request.POST['ship_address']
        ship_phone=request.POST['ship_phone']
        card_number=request.POST['card_number']
        expire=request.POST['expire']
        security_code=request.POST['security_code']

        if request.user.is_authenticated and not request.user.is_anonymous:
            if Order.objects.all().filter(user=request.user,is_finished=False).exists():

                order=Order.objects.get(user=request.user,is_finished=False)
                payment=Payment(order=order,shipment_address=ship_address,shipment_phone=ship_phone,card_number=card_number,expire=expire,security=security_code)
                payment.save()
                order.is_finished=True
                order.save()
                is_added=True
                messages.success(request,'Your order is finished')
        context={
            'ship_address':ship_address,
            'ship_phone':ship_phone,
            'card_number':card_number,
            'expire':expire,
            'security_code':security_code,
            'is_added':is_added,
        }
    else:
        if request.user.is_authenticated and not request.user.is_anonymous:
            if Order.objects.all().filter(user=request.user,is_finished=False).exists():

                order=Order.objects.get(user=request.user,is_finished=False)

                orderdetails=OrderDetails.objects.all().filter(order=order)
                total=0
                for orderdetail in orderdetails:
                    total+=orderdetail.price * orderdetail.quantity
                context={
                    'orderdetails':orderdetails,
                    'order':order,
                    'total':total,
                }
    return render(request,'orders/payment.html',context)

def show_orders(request):

    context=None
    all_orders=None
    if request.user.is_authenticated and not request.user.is_anonymous:
        all_orders=Order.objects.all().filter(user=request.user)
        if all_orders:
            for x in all_orders:
                order=Order.objects.get(id=x.id)
                orderdetails=OrderDetails.objects.all().filter(order=order)
                total=0
                for orderdetail in orderdetails:
                    total+=orderdetail.price * orderdetail.quantity
                x.total=total
                x.items_count=orderdetails.count
    context={
        'all_orders':all_orders
    }

    return render(request,'orders/show_orders.html',context)

templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cart{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <h2 class="text-center">Cart</h2>
    <hr>
    {% if not request.user.is_authenticated and request.user.is_anonymous %}
        <h5 class="alert alert-warning">
            You must be
            <a href="{% url 'accounts:signin' %}" class="text-dark">Logged in</a>
        </h5>
    {% elif order %}
    <h5>
        Full name: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">
          {{ order.user.username|add:' '|add:order.user.last_name }}
        </span>
        <a href="{% url 'products:products' %}" class="btn btn-outline-warning float-right m-1">Continue Shopping</a>
        <a href="{% url 'add_to_cart:payment' %}" class="btn btn-outline-secondary float-right m-1">Checkout</a>
        <br>
        <br>
        <hr>
        Order Number: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">
          {{ order.id }}</span> with total: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">{{ total }}$
          </span>
        for: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">
          {{ orderdetails.count }}
        </span> products
    </h5>   
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Image</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Subtotals</th>
            <th scope="col">Control</th>
          </tr>
        </thead>
        <tbody>
        {% for line in orderdetails %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ line.product.name }}</td>
            <td><img src="{{ line.product.photo.url }}" style="width: 80px;height:80px ;" alt=""></td>
            <td>
                <a href="{% url 'add_to_cart:sub_qty' line.id %}" class="btn btn-outline-warning btn-sm">-</a>
                {{ line.quantity }}
                <a href="{% url 'add_to_cart:add_qty' line.id %}" class="btn btn-outline-warning btn-sm">+</a>
            </td>
            <td>{{ line.price }}$</td>
            <td style="font-weight: bold; color: darkred;">{% widthratio line.quantity 1 line.price %}$</td>
            <td>
                <a href="{% url 'add_to_cart:remove_from_cart' line.id  %}" class="btn btn-outline-danger btn-sm">Remove</a>
            </td>
          </tr>
        {% empty %}
        <h5 class="alert alert-warning">
            No details here
        </h5>
        {% endfor %}
        </tbody>
      </table>

    {% else %}
    <h5 class="alert alert-warning">
        No orders here,
        <a href="{% url 'products:products' %}" class="text-dark">All products</a>
    </h5>

    {% endif %}
    <hr>
</div>
{% endblock %}

templates/orders/payment.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <h2 class="text-center">Checkout</h2>
        <hr>
        {% include 'partials/_alerts.html' %}
{% if not request.user.is_authenticated and request.user.is_anonymous %}
<h5 class="alert alert-warning">
    You must be,
    <a href="{% url 'accounts:signin' %}" class="text-dark">Logged in</a>
</h5>
{% elif not order %}
<h4 class="alert alert-warning">No Orders Here</h4>
{% else %}
{% if is_added == True %}  
    <form method="POST" style="display: none;">
{% else  %}
    <form method="POST">
{% endif %}
        {% csrf_token %}
        
        Order Number: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">{{ order.id }}</span>
        <hr> 
        Product Count: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">{{ orderdetails.count }}</span>
        <hr>
        Total Amount: <span style="color: darkred; font-weight: bold; border: 1px solid darkred; padding: 2px 10px; border-radius: 50px;">{{ total }}$</span>
        <hr>
        <a href="{% url 'add_to_cart:cart' %}" class="btn btn-secondary">Cart Details</a>
        <hr>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputship_address">Shipment Adress</label>
                <input type="text" name="ship_address" class="form-control" id="inputship_address" value="{{ ship_address }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="inputship_phone">Shipment Phone</label>
                <input type="text" name="ship_phone" class="form-control" id="inputship_phone" value="{{ ship_phone }}" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputcard_number">Card Number</label>
                <input type="text" name="card_number" class="form-control" id="inputcard_number" value="{{ card_number }}" placeholder="3333 3333 3333 3333" required>
            </div>
            <div class="form-group col-md-4">
                <label for="inputexpire">Expire</label>
                <input type="text" name="expire" class="form-control" id="inputexpire" value="{{ expire }}" placeholder="mm/YY" required>
            </div>
            <div class="form-group col-md-2">
                <label for="inputsecurity_code">Security Code</label>
                <input type="text" name="security_code" class="form-control" id="inputsecurity_code" placeholder="333" value="{{ security_code }}" required>
            </div>
        </div>
        <button type="submit" name="btnpayment" class="btn btn-warning">Payment</button>
    </form>
{% endif %}


</div>
{% endblock %}

templates/orders/show_orders.html
{% extends 'base.html' %}

{% block title %}All Orders{% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">
    <h2 class="text-center">Orders</h2>
    <hr>
    {% if not request.user.is_authenticated and request.user.is_anonymous %}
        <h5 class="alert alert-warning">
            You must be
            <a href="{% url 'accounts:signin' %}" class="text-dark">Logged in</a>
        </h5>
    {% elif all_orders %}
        {% if all_orders.count > 1 %}
            <h5 class="alert alert-warning">Found {{ all_orders.count }} Orders</h5>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Order Number</th>
                    <th scope="col">Date & Time</th>
                    <th scope="col">Items Count</th>
                    <th scope="col">Total</th>
                    <th scope="col">Is Finished</th>
                </tr>
                </thead>
                <tbody>
        {% endif %}

        {% for order in all_orders  %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.order_date }}</td>
                        <td>{{ order.items_count }}</td>
                        <td>{{ order.total }}</td>
                        <td>
                            {% if order.is_finished == True %}
                            Yes
                            {% else %}
                            No
                            {% endif %}
                        </td>
                    </tr>
        {% endfor %}
        {% if all_orders.count > 1 %}
                </tbody>
            </table>
        {% endif %}

    {% else %}
    <h5 class="alert alert-warning">
        No orders here,
        <a href="{% url 'products:products' %}" class="text-dark">All products</a>
    </h5>

    {% endif %}
    <hr>
</div>
{% endblock %}